### ISSUE TITLE
Github Dark Mode Image Support

### ISSUE THREAD

**Issue by mwarkentin** [pypa/readme_renderer#239]

**Comment by di** [comment]
I've transferred this issue to https://github.com/pypa/readme_renderer/, but this is likely blocked on a change to our underlying GitHub-flavored Markdown formatter, https://github.com/theacodes/cmarkgfm

**Comment by mwarkentin** [comment]
@di thanks - should I open an issue over there?

**Comment by di** [comment]
Yep

**Comment by mwarkentin** [comment]
@di looks like this is just done in CSS on Github:

> [GH implements this very naïvely/smartly with CSS. Basically:](https://github.com/github/cmark-gfm/issues/261#issuecomment-1108630429)

```css
@media (prefers-color-scheme: light) {
  /* ^-- browser/os setting */
  :root[data-color-mode=auto] .markdown [href$="#\gh-dark-mode-only"] {
    /* ^-- gh theme */
    display: none
  }
}
```
